import type { TenantConfig, NavItem } from './types';

export const defaultModules: TenantConfig['modules'] = [
  {
    id: 'dashboard',
    name: 'Dashboard',
    description: 'Overview and analytics',
    enabled: true,
    icon: 'LayoutDashboard',
  },
  {
    id: 'pos',
    name: 'Point of Sale',
    description: 'POS billing and quick sales',
    enabled: true,
    icon: 'ShoppingCart',
  },
  {
    id: 'sales',
    name: 'Sales & Invoicing',
    description: 'Invoices, quotations, returns',
    enabled: true,
    icon: 'Receipt',
  },
  {
    id: 'inventory',
    name: 'Inventory',
    description: 'Products, stock, transfers',
    enabled: true,
    icon: 'Package',
  },
  {
    id: 'repairs',
    name: 'Repairs & Service',
    description: 'Job cards, technician board',
    enabled: true,
    icon: 'Wrench',
  },
  {
    id: 'customers',
    name: 'Customers',
    description: 'Customer management and credit',
    enabled: true,
    icon: 'Users',
  },
  {
    id: 'suppliers',
    name: 'Suppliers & Procurement',
    description: 'Purchase orders, GRN, imports',
    enabled: true,
    icon: 'Truck',
  },
  {
    id: 'reports',
    name: 'Reports',
    description: 'Sales, inventory, financial reports',
    enabled: true,
    icon: 'BarChart3',
  },
  {
    id: 'config',
    name: 'Configuration',
    description: 'System settings and users',
    enabled: true,
    icon: 'Settings',
    requiredRoles: ['admin', 'manager'],
  },
];

export const defaultFeatures: TenantConfig['features'] = [
  { id: 'credit_sales', name: 'Credit Sales', description: 'Allow sales on credit', enabled: true, moduleId: 'sales' },
  { id: 'discounts', name: 'Discounts', description: 'Enable discount on items', enabled: true, moduleId: 'pos' },
  { id: 'returns', name: 'Returns & Refunds', description: 'Process returns', enabled: true, moduleId: 'sales' },
  { id: 'split_payments', name: 'Split Payments', description: 'Multiple payment methods', enabled: true, moduleId: 'pos' },
  { id: 'serial_tracking', name: 'Serial Tracking', description: 'Track serial numbers', enabled: true, moduleId: 'inventory' },
  { id: 'batch_tracking', name: 'Batch Tracking', description: 'Track batches and expiry', enabled: true, moduleId: 'inventory' },
  { id: 'stock_transfers', name: 'Stock Transfers', description: 'Transfer between branches', enabled: true, moduleId: 'inventory' },
  { id: 'stock_adjustments', name: 'Stock Adjustments', description: 'Adjust stock levels', enabled: true, moduleId: 'inventory' },
  { id: 'job_cards', name: 'Job Cards', description: 'Repair job management', enabled: true, moduleId: 'repairs' },
  { id: 'warranty_tracking', name: 'Warranty Tracking', description: 'Track warranty claims', enabled: true, moduleId: 'repairs' },
  { id: 'multi_branch', name: 'Multi-Branch', description: 'Multiple locations', enabled: true, moduleId: 'config' },
  { id: 'landed_costs', name: 'Landed Costs', description: 'Track import costs', enabled: true, moduleId: 'suppliers' },
  { id: 'vat_enabled', name: 'VAT/Tax', description: 'Enable tax calculations', enabled: true, moduleId: 'config' },
  { id: 'approval_workflows', name: 'Approval Workflows', description: 'Require approvals', enabled: true, moduleId: 'config' },
  { id: 'offline_mode', name: 'Offline Mode', description: 'Work offline', enabled: false, moduleId: 'pos' },
];

export const defaultWorkflows: TenantConfig['workflows'] = [
  {
    id: 'job_card_workflow',
    name: 'Job Card Workflow',
    entityType: 'job_card',
    statuses: [
      { id: 'received', name: 'Received', color: 'bg-muted', order: 1 },
      { id: 'diagnosing', name: 'Diagnosing', color: 'bg-blue-500', order: 2 },
      { id: 'awaiting_parts', name: 'Awaiting Parts', color: 'bg-yellow-500', order: 3 },
      { id: 'repairing', name: 'Repairing', color: 'bg-orange-500', order: 4 },
      { id: 'testing', name: 'Testing', color: 'bg-purple-500', order: 5 },
      { id: 'completed', name: 'Completed', color: 'bg-green-500', order: 6 },
      { id: 'delivered', name: 'Delivered', color: 'bg-primary', order: 7 },
    ],
    transitions: [
      { from: 'received', to: 'diagnosing', label: 'Start Diagnosis' },
      { from: 'diagnosing', to: 'awaiting_parts', label: 'Need Parts' },
      { from: 'diagnosing', to: 'repairing', label: 'Start Repair' },
      { from: 'awaiting_parts', to: 'repairing', label: 'Parts Received' },
      { from: 'repairing', to: 'testing', label: 'Start Testing' },
      { from: 'testing', to: 'repairing', label: 'Failed Test' },
      { from: 'testing', to: 'completed', label: 'Pass Testing' },
      { from: 'completed', to: 'delivered', label: 'Deliver to Customer' },
    ],
  },
  {
    id: 'po_workflow',
    name: 'Purchase Order Workflow',
    entityType: 'purchase_order',
    statuses: [
      { id: 'draft', name: 'Draft', color: 'bg-muted', order: 1 },
      { id: 'pending_approval', name: 'Pending Approval', color: 'bg-yellow-500', order: 2 },
      { id: 'approved', name: 'Approved', color: 'bg-green-500', order: 3 },
      { id: 'ordered', name: 'Ordered', color: 'bg-blue-500', order: 4 },
      { id: 'partial_received', name: 'Partial Received', color: 'bg-orange-500', order: 5 },
      { id: 'received', name: 'Received', color: 'bg-primary', order: 6 },
      { id: 'cancelled', name: 'Cancelled', color: 'bg-destructive', order: 7 },
    ],
    transitions: [
      { from: 'draft', to: 'pending_approval', label: 'Submit for Approval' },
      { from: 'pending_approval', to: 'approved', label: 'Approve', requiredRoles: ['admin', 'manager'] },
      { from: 'pending_approval', to: 'draft', label: 'Reject', requiredRoles: ['admin', 'manager'] },
      { from: 'approved', to: 'ordered', label: 'Mark as Ordered' },
      { from: 'ordered', to: 'partial_received', label: 'Partial GRN' },
      { from: 'ordered', to: 'received', label: 'Full GRN' },
      { from: 'partial_received', to: 'received', label: 'Complete GRN' },
      { from: 'draft', to: 'cancelled', label: 'Cancel' },
      { from: 'pending_approval', to: 'cancelled', label: 'Cancel' },
    ],
  },
  {
    id: 'stock_adjustment_workflow',
    name: 'Stock Adjustment Workflow',
    entityType: 'stock_adjustment',
    statuses: [
      { id: 'pending', name: 'Pending', color: 'bg-yellow-500', order: 1 },
      { id: 'approved', name: 'Approved', color: 'bg-green-500', order: 2 },
      { id: 'rejected', name: 'Rejected', color: 'bg-destructive', order: 3 },
    ],
    transitions: [
      { from: 'pending', to: 'approved', label: 'Approve', requiredRoles: ['admin', 'manager'], requiresApproval: true },
      { from: 'pending', to: 'rejected', label: 'Reject', requiredRoles: ['admin', 'manager'] },
    ],
  },
];

export const defaultApprovalRules: TenantConfig['approvalRules'] = [
  {
    id: 'discount_limit',
    name: 'Discount Limit',
    description: 'Require approval for discounts over 10%',
    entityType: 'invoice',
    condition: { field: 'discount_percent', operator: 'gt', value: 10 },
    approverRoles: ['admin', 'manager'],
    enabled: true,
  },
  {
    id: 'credit_limit',
    name: 'Credit Limit Check',
    description: 'Block sale when credit limit exceeded',
    entityType: 'invoice',
    condition: { field: 'exceeds_credit_limit', operator: 'eq', value: true },
    approverRoles: ['admin', 'manager'],
    enabled: true,
  },
  {
    id: 'stock_adjustment_approval',
    name: 'Stock Adjustment Approval',
    description: 'All stock adjustments require approval',
    entityType: 'stock_adjustment',
    condition: { field: 'requires_approval', operator: 'eq', value: true },
    approverRoles: ['admin', 'manager'],
    enabled: true,
  },
  {
    id: 'large_po_approval',
    name: 'Large PO Approval',
    description: 'PO over $5000 requires approval',
    entityType: 'purchase_order',
    condition: { field: 'total_amount', operator: 'gt', value: 5000 },
    approverRoles: ['admin'],
    enabled: true,
  },
];

export const defaultDocumentNumbering: TenantConfig['documentNumbering'] = {
  invoice: { prefix: 'INV-', currentNumber: 1, padLength: 6 },
  quotation: { prefix: 'QUO-', currentNumber: 1, padLength: 6 },
  purchaseOrder: { prefix: 'PO-', currentNumber: 1, padLength: 6 },
  grn: { prefix: 'GRN-', currentNumber: 1, padLength: 6 },
  jobCard: { prefix: 'JOB-', currentNumber: 1, padLength: 6 },
  stockTransfer: { prefix: 'STR-', currentNumber: 1, padLength: 6 },
  stockAdjustment: { prefix: 'ADJ-', currentNumber: 1, padLength: 6 },
};

export const defaultLocalization: TenantConfig['localization'] = {
  currency: 'USD',
  currencySymbol: '$',
  currencyPosition: 'before',
  decimalPlaces: 2,
  thousandsSeparator: ',',
  decimalSeparator: '.',
  dateFormat: 'MM/DD/YYYY',
  timeFormat: '12h',
  timezone: 'UTC',
  language: 'en',
};

export const defaultTenantConfig: TenantConfig = {
  id: 'default',
  name: 'DevLabCo ERP',
  modules: defaultModules,
  features: defaultFeatures,
  workflows: defaultWorkflows,
  approvalRules: defaultApprovalRules,
  documentNumbering: defaultDocumentNumbering,
  localization: defaultLocalization,
  operationMode: 'full_erp',
};

export const navigationConfig: NavItem[] = [
  {
    id: 'dashboard',
    title: 'Dashboard',
    icon: 'LayoutDashboard',
    href: '/',
    moduleId: 'dashboard',
  },
  {
    id: 'sales',
    title: 'Sales & POS',
    icon: 'ShoppingCart',
    moduleId: 'sales',
    children: [
      { id: 'pos', title: 'POS Billing', href: '/pos', featureId: undefined },
      { id: 'cash-drawer', title: 'Cash Drawer', href: '/cash-drawer' },
      { id: 'petty-cash', title: 'Petty Cash', href: '/petty-cash' },
      { id: 'invoices', title: 'Sales Invoices', href: '/sales/invoices' },
      { id: 'quotations', title: 'Quotations', href: '/sales/quotations' },
      { id: 'returns', title: 'Returns & Refunds', href: '/sales/returns', featureId: 'returns' },
      { id: 'payments', title: 'Payments', href: '/sales/payments' },
    ],
  },
  {
    id: 'inventory',
    title: 'Inventory',
    icon: 'Package',
    moduleId: 'inventory',
    children: [
      { id: 'products', title: 'Products', href: '/inventory/products' },
      { id: 'categories', title: 'Categories & Brands', href: '/inventory/categories' },
      { id: 'stock', title: 'Stock Overview', href: '/inventory/stock' },
      { id: 'locations', title: 'Stock Locations', href: '/inventory/locations' },
      { id: 'serials', title: 'Serial Registry', href: '/inventory/serials', featureId: 'serial_tracking' },
      { id: 'transfers', title: 'Stock Transfers', href: '/inventory/transfers', featureId: 'stock_transfers' },
      { id: 'adjustments', title: 'Stock Adjustments', href: '/inventory/adjustments', featureId: 'stock_adjustments' },
    ],
  },
  {
    id: 'repairs',
    title: 'Repairs & Service',
    icon: 'Wrench',
    moduleId: 'repairs',
    children: [
      { id: 'jobs', title: 'Job Cards', href: '/repairs/jobs', featureId: 'job_cards' },
      { id: 'board', title: 'Technician Board', href: '/repairs/board' },
      { id: 'estimates', title: 'Estimates', href: '/repairs/estimates' },
      { id: 'billing', title: 'Service Billing', href: '/repairs/billing' },
      { id: 'warranty', title: 'Warranty Jobs', href: '/repairs/warranty', featureId: 'warranty_tracking' },
    ],
  },
  {
    id: 'customers',
    title: 'Customers',
    icon: 'Users',
    moduleId: 'customers',
    children: [
      { id: 'list', title: 'Customer List', href: '/customers' },
      { id: 'credit', title: 'Credit Accounts', href: '/customers/credit', featureId: 'credit_sales' },
      { id: 'receivables', title: 'Receivables Aging', href: '/customers/receivables' },
      { id: 'history', title: 'Service History', href: '/customers/history' },
    ],
  },
  {
    id: 'suppliers',
    title: 'Suppliers',
    icon: 'Truck',
    moduleId: 'suppliers',
    children: [
      { id: 'list', title: 'Supplier List', href: '/suppliers/list' },
      { id: 'orders', title: 'Purchase Orders', href: '/suppliers/orders' },
      { id: 'grn', title: 'GRN', href: '/suppliers/grn' },
      { id: 'payables', title: 'Payables Aging', href: '/suppliers/payables' },
      { id: 'batches', title: 'Import Batches', href: '/suppliers/batches', featureId: 'landed_costs' },
    ],
  },
  {
    id: 'reports',
    title: 'Reports',
    icon: 'BarChart3',
    moduleId: 'reports',
    children: [
      { id: 'sales', title: 'Sales Reports', href: '/reports/sales' },
      { id: 'inventory', title: 'Inventory Reports', href: '/reports/inventory' },
      { id: 'repairs', title: 'Repair Reports', href: '/reports/repairs' },
      { id: 'financial', title: 'Financial Summary', href: '/reports/financial' },
      { id: 'scheduled', title: 'Scheduled Reports', href: '/reports/scheduled' },
    ],
  },
  {
    id: 'config',
    title: 'Configuration',
    icon: 'Settings',
    moduleId: 'config',
    requiredRoles: ['admin', 'manager'],
    children: [
      { id: 'users', title: 'Users & Roles', href: '/config/users', requiredRoles: ['admin'] },
      { id: 'user-approvals', title: 'User Approvals', href: '/config/user-approvals', requiredRoles: ['admin'] },
      { id: 'company', title: 'Company Settings', href: '/config/company', requiredRoles: ['admin'] },
      { id: 'system', title: 'System Settings', href: '/config/system', requiredRoles: ['admin'] },
      { id: 'security', title: 'Security & Auth', href: '/config/security', requiredRoles: ['admin'] },
      { id: 'modules', title: 'Modules', href: '/config/modules', requiredRoles: ['admin'] },
      { id: 'workflows', title: 'Workflows', href: '/config/workflows', requiredRoles: ['admin'] },
      { id: 'approval-rules', title: 'Approval Rules', href: '/config/approvals', requiredRoles: ['admin', 'manager'] },
      { id: 'pending-approvals', title: 'Pending Approvals', href: '/approvals', requiredRoles: ['admin', 'manager'], featureId: 'approval_workflows' },
      { id: 'audit-trail', title: 'Audit Trail', href: '/config/audit-trail', requiredRoles: ['admin'] },
      { id: 'tax', title: 'Tax & Pricing', href: '/config/tax', featureId: 'vat_enabled' },
      { id: 'branches', title: 'Branch Setup', href: '/config/branches', featureId: 'multi_branch' },
    ],
  },
];
